run migrations

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -140,6 +140,10 @@ jobs:
 
             echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
             docker compose pull
+
+            echo "Running database migrations..."
+            docker compose run --rm drizzle pnpm db:push || exit 1 # Exit if migration fails
+            echo "Database migrations complete."
             docker compose down --remove-orphans
             docker compose up -d
             docker image prune -f
